"""Add progress field to checkins

Revision ID: 2681660f5f48
Revises: 8bae3c5a8044
Create Date: 2026-01-24 23:45:45.911976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2681660f5f48'
down_revision: Union[str, None] = '8bae3c5a8044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('progress', sa.String(length=20), nullable=False))
    op.alter_column('checkins', 'mood',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkins', 'mood',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('checkins', 'progress')
    # ### end Alembic commands ###
